### ISSUE TITLE
Name collision with Matplotlib

### ISSUE THREAD

**Issue by tacaswell** [LukeSkywalker92/pylab#5]
As part of Matplotlib we ship a top-level `pylab.py` which people import as `import pylab`.  Your package (which from skimming the code is quite sensibly named!) collides with this name.  Further,  there will be users who run `pip install pylab` intending to get plotting and instead get your package which benefits no one (the users don't get what they want, we get bug reports, you get bug reports...).

Could you please rename your package, pull it from pypi as `pylab`, and add me as an owner of the pylab name on pypi? 

This is not the first time this has happened (see https://github.com/javipalanca/scibag/issues/1) and we failed to put put up a placeholder package (like https://pypi.org/project/pyplot/1.5.0/ ) after it was taken down.  

If you want to talk about this in a non-public channel email me at tcaswell@gmail.com .

xref https://github.com/matplotlib/matplotlib/issues/16422

**Comment by LukeSkywalker92** [comment]
Hey,

I'm sorry for the problems I raised for you.
Since I'm using matplotlib almost daily and love it I will definitely do what is needed to help you.
Why did I never needed to import pylab before?! W
There are just 2 minor problems: I'm leaving for a trip where I won't have access to internet, so I won't make it this week. But on Tuesday next week I should find time for it. Maybe you can tell me exactly what to do...then I will make it faster...
Second Problem: I need a new name for this project that fits as nice as pylab 😛 do you have an idea? 😃 

Is there a way to prevent this naming issue in the future? Can you block it on pypi?

**Comment by tacaswell** [comment]
Thank you for being understanding!

If you add me as a collaborator on pypi before you take off  (`thomas.caswell`) I can take of it.  The very short version is delete / hide the files from pypi.

We would keep the name, but leave an empty package there (so `pip install pylab` will fail) and prevent someone else from grabbing the name.

You may be interested in https://lucask07.github.io/instrbuilder/build/html/ which I think is going after the same problems.

`labpy` ?

**Comment by LukeSkywalker92** [comment]
I deleted all releases and added you as a collaborator.

**Comment by tacaswell** [comment]
Thank you so much!
